// src/constants/iconOptions.ts
import {
  Activity,
  AlarmClock,
  Archive,
  Backpack,
  Banknote,
  BarChart,
  Bed,
  Bike,
  Book,
  Briefcase,
  Calendar,
  Car,
  Cat,
  CheckCircle,
  ChefHat,
  CircleDollarSign,
  Coffee,
  CreditCard,
  Dice5,
  Flame,
  Gamepad,
  Gift,
  Hammer,
  Headphones,
  Heart,
  Home,
  Leaf,
  Lightbulb,
  Map,
  Martini,
  Monitor,
  Music,
  PawPrint,
  Pizza,
  Plane,
  PlusIcon,
  Receipt,
  School,
  Shirt,
  ShoppingCart,
  Smartphone,
  Sofa,
  Soup,
  Sun,
  Train,
  Tv,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
} from "lucide-react";

export const iconOptions = [
  { name: "ShoppingCart", label: "Покупки", icon: ShoppingCart },
  { name: "Wallet", label: "Кошелек", icon: Wallet },
  { name: "CreditCard", label: "Карта", icon: CreditCard },
  { name: "Utensils", label: "Еда", icon: Utensils },
  { name: "Pizza", label: "Пицца", icon: Pizza },
  { name: "Soup", label: "Суп", icon: Soup },
  { name: "Coffee", label: "Кофе", icon: Coffee },
  { name: "Wine", label: "Вино", icon: Wine },
  { name: "Martini", label: "Бар", icon: Martini },
  { name: "Train", label: "Поезд", icon: Train },
  { name: "Plane", label: "Самолет", icon: Plane },
  { name: "Car", label: "Машина", icon: Car },
  { name: "Bike", label: "Велосипед", icon: Bike },
  { name: "Smartphone", label: "Телефон", icon: Smartphone },
  { name: "Monitor", label: "Монитор", icon: Monitor },
  { name: "Tv", label: "Телевизор", icon: Tv },
  { name: "Music", label: "Музыка", icon: Music },
  { name: "Gamepad", label: "Игры", icon: Gamepad },
  { name: "Gift", label: "Подарок", icon: Gift },
  { name: "Shirt", label: "Одежда", icon: Shirt },
  { name: "Sofa", label: "Мебель", icon: Sofa },
  { name: "Home", label: "Дом", icon: Home },
  { name: "Bed", label: "Кровать", icon: Bed },
  { name: "ChefHat", label: "Готовка", icon: ChefHat },
  { name: "Hammer", label: "Ремонт", icon: Hammer },
  { name: "Wrench", label: "Инструменты", icon: Wrench },
  { name: "School", label: "Школа", icon: School },
  { name: "Book", label: "Книги", icon: Book },
  { name: "Calendar", label: "Календарь", icon: Calendar },
  { name: "AlarmClock", label: "Будильник", icon: AlarmClock },
  { name: "Leaf", label: "Природа", icon: Leaf },
  { name: "Flame", label: "Огонь", icon: Flame },
  { name: "Sun", label: "Солнце", icon: Sun },
  { name: "Lightbulb", label: "Идея", icon: Lightbulb },
  { name: "Backpack", label: "Рюкзак", icon: Backpack },
  { name: "Cat", label: "Кот", icon: Cat },
  { name: "PawPrint", label: "Животные", icon: PawPrint },
  { name: "Headphones", label: "Наушники", icon: Headphones },
  { name: "Heart", label: "Сердце", icon: Heart },
  { name: "CheckCircle", label: "Задача", icon: CheckCircle },
  { name: "Activity", label: "Активность", icon: Activity },
  { name: "Dice5", label: "Удача", icon: Dice5 },
  { name: "CircleDollarSign", label: "Доход", icon: CircleDollarSign },
  { name: "Banknote", label: "Банкнота", icon: Banknote },
  { name: "BarChart", label: "График", icon: BarChart },
  { name: "Map", label: "Карта", icon: Map },
  { name: "Receipt", label: "Чек", icon: Receipt },
  { name: "Archive", label: "Архив", icon: Archive },
  { name: "Wifi", label: "Wi-Fi", icon: Wifi },
  { name: "Briefcase", label: "Работа", icon: Briefcase },
  { name: "Briefcase", label: "Работа", icon: PlusIcon },
];
export const iconMap = Object.fromEntries(
  iconOptions.map(({ name, icon }) => [name, icon])
);
